### PR TITLE
Adds workflow for snapshot releases

### PR DESCRIPTION
**Pull request by FrankSchnicke**
Please squash and merge

### CODE REVIEW

**Review by sebbader — APPROVED** [review]

**Comment by sebbader** [comment]
Hi @FrankSchnicke, 

looks good to me! Two questions:
The workflow will require a GITHUB_ACTOR as another secret, right?

Second, you import gradle via a step (line 24 of gradle-publish-package.yml). Couldn't we use the gradlew executable directly?

Nothing critical though. Critcal is however that I don't have permissions to merge anything in this repo :-)

**Comment by sebbader** [comment]
Maybe @alw-iwu ?

**Comment by FrankSchnicke** [comment]
Thanks for your feedback.

GITHUB_ACTOR is a preconfigured environment variable (see https://docs.github.com/en/actions/learn-github-actions/environment-variables). Thus, there's no additional configuration necessary.

You're right, we could use gradlew directly. However, I'm not 100% sure why gradlew is used in this project. I can gladly change this if required. 

I requested @alw-iwu as Reviewer :-)

**Comment by alw-iwu** [comment]
Yea, actually it'd be great if we could use gradlew directly. [Documentation says it's common practice.](https://docs.gradle.org/current/userguide/jenkins.html#build_the_project)

**Pull request merged**
